spring.application.name=gestion-producto-spring

spring.datasource.url=jdbc:postgresql://localhost:5432/gestion_producto
spring.datasource.username=baxava
spring.datasource.password=medifind_baxava

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
